/**
 * Sportfest Backend
 * Sportfest backend
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Disziplin } from './disziplin';
import { Klasse } from './klasse';
import { Leistung } from './leistung';
import { Schueler } from './schueler';


export interface Ergebnis {
    id?: number;
    punkte?: number;
    leistungen?: Array<Leistung>;
    klasse?: Klasse;
    schueler?: Schueler;
    disziplin?: Disziplin;
}
