/**
 * Sportfest Backend
 * Sportfest backend
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Typ {
    id?: number;
    datentyp?: Typ.DatentypEnum;
    einheit?: string;
    /**
     * RegEx
     */
    format?: string;
    /**
     * Beispiel
     */
    bsp?: string;
}
export namespace Typ {
    export type DatentypEnum = 'STRING' | 'INT' | 'FLOAT' | 'LONG' | 'DOUBLE';
    export const DatentypEnum = {
        STRING: 'STRING' as DatentypEnum,
        INT: 'INT' as DatentypEnum,
        FLOAT: 'FLOAT' as DatentypEnum,
        LONG: 'LONG' as DatentypEnum,
        DOUBLE: 'DOUBLE' as DatentypEnum
    }
}
